const ACTIONS = {
    UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD',
    UPDATE_RESULT_DB: 'UPDATE_RESULT_DB',
    UPDATE_CURRENT_OBJECT_STORE: 'UPDATE_CURRENT_OBJECT_STORE',
    UPDATE_INDB_STORE_OBJECTS: 'UPDATE_INDB_STORE_OBJECTS',
    DELETE_FORM_FIELD: 'DELETE_FORM_FIELD',
};
export default ACTIONS;

