const ACTIONS = {
    UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD',
    UPDATE_FORM_FIELD_LIST: 'UPDATE_FORM_FIELD_LIST',
    UPDATE_RESULT_DB: 'UPDATE_RESULT_DB',
    UPDATE_CURRENT_FORMNAME: 'UPDATE_CURRENT_FORMNAME',
    UPDATE_INDB_STORE_OBJECTS: 'UPDATE_INDB_STORE_OBJECTS',
    DELETE_FORM_FIELD: 'DELETE_FORM_FIELD',
    DELETE_FORM_FIELD_LIST: 'DELETE_FORM_FIELD_LIST',
    UPDATE_DEPARTMENTS: 'UPDATE_DEPARTMENTS',
    UPDATE_SELECTION: 'UPDATE_SELECTION',
    UPDATE_EXPORT_MODE: 'UPDATE_EXPORT_MODE',
    UPDATE_SIDE_NAVIGATION_MODE: 'UPDATE_SIDE_NAVIGATION_MODE',
    UPDATE_COLOR_THEME: 'UPDATE_COLOR_THEME',
};
export default ACTIONS;

