const ACTIONS = {
    UPDATE_FORM: 'UPDATE_FORM',
    UPDATE_RESULT_DB: 'UPDATE_RESULT_DB',
    UPDATE_CURRENT_OBJECT_STORE: 'UPDATE_CURRENT_OBJECT_STORE',
    UPDATE_INDB_STORE_OBJECTS: 'UPDATE_INDB_STORE_OBJECTS',
};
export default ACTIONS;

