# PUT https://api.paysage.staging.dataesr.ovh/structures/7CYWd HTTP/1.1
# content-type: application/json
# authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY2MzQwT1kiLCJ1cGRhdGVkQXQiOiIyMDIyLTAxLTA1VDEwOjIwOjA5LjM4NVoiLCJjcmVhdGVkQXQiOiIyMDIyLTAxLTA1VDEwOjIwOjA5LjUzM1oiLCJlbWFpbCI6ImplcmVteS5wZWdsaW9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkplcmVteSIsImxhc3ROYW1lIjoiUEVHTElPTiIsInVzZXJuYW1lIjoiamVyZW0iLCJyb2xlIjoidXNlciIsImFjdGl2ZSI6dHJ1ZSwiY29uZmlybWVkIjpmYWxzZX0sInR5cGUiOiJhY2Nlc3MtdG9rZW4iLCJpYXQiOjE2NDU0NDA4NjAsImV4cCI6MTY0NTQ0MTQ2MH0.qD_8-zmM-z6nG4WNyUpfZivXsPnJEdU-PWV3eizRLYI


GET https://api.paysage.staging.dataesr.ovh/structures/8tVLr
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY2MzQwT1kiLCJ1cGRhdGVkQXQiOiIyMDIyLTAxLTA1VDEwOjIwOjA5LjM4NVoiLCJjcmVhdGVkQXQiOiIyMDIyLTAxLTA1VDEwOjIwOjA5LjUzM1oiLCJlbWFpbCI6ImplcmVteS5wZWdsaW9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkplcmVteSIsImxhc3ROYW1lIjoiUEVHTElPTiIsInVzZXJuYW1lIjoiamVyZW0iLCJyb2xlIjoidXNlciIsImFjdGl2ZSI6dHJ1ZSwiY29uZmlybWVkIjpmYWxzZX0sInR5cGUiOiJhY2Nlc3MtdG9rZW4iLCJpYXQiOjE2NDU0NDA4NjAsImV4cCI6MTY0NTQ0MTQ2MH0.qD_8-zmM-z6nG4WNyUpfZivXsPnJEdU-PWV3eizRLYI
