POST https://api.paysage.staging.dataesr.ovh/auth/refresh-access-token HTTP/1.1
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY2MzQwT1kiLCJ1cGRhdGVkQXQiOiIyMDIyLTAxLTA1VDEwOjIwOjA5LjM4NVoiLCJjcmVhdGVkQXQiOiIyMDIyLTAxLTA1VDEwOjIwOjA5LjUzM1oiLCJlbWFpbCI6ImplcmVteS5wZWdsaW9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkplcmVteSIsImxhc3ROYW1lIjoiUEVHTElPTiIsInVzZXJuYW1lIjoiamVyZW0iLCJyb2xlIjoidXNlciIsImFjdGl2ZSI6dHJ1ZSwiY29uZmlybWVkIjpmYWxzZX0sInR5cGUiOiJyZWZyZXNoLXRva2VuIiwiaWF0IjoxNjQ1NDQwMDM3LCJleHAiOjE2NDcxNjgwMzd9.JlBSzmwOMTjy1a6zwfOfL7_3ko32G6cZSLMV7aibnaU!"
}