name: Tests
on:
  push:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: yarn
      - name: Run unit tests
        run: yarn run test
      - name: Run Cypress tests
        run: yarn run cy:run-only:prod
      - name: Notify Slack
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-tests'
        if: always()
